# Generated by Django 5.1.2 on 2024-10-14 07:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=255, verbose_name="Полное имя"),
                ),
                (
                    "profession",
                    models.CharField(max_length=255, verbose_name="Профессия"),
                ),
                (
                    "resume_file",
                    models.FileField(upload_to="perosnal", verbose_name="Файл резюме"),
                ),
                (
                    "about_me",
                    ckeditor.fields.RichTextField(verbose_name="Текст обо мне"),
                ),
            ],
            options={
                "verbose_name": "Персональная информальная",
                "verbose_name_plural": "Персональная информация",
            },
        ),
    ]
