# Generated by Django 5.1.2 on 2024-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="email",
            field=models.CharField(default="", max_length=255, verbose_name="Почта"),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="github",
            field=models.CharField(
                default="", max_length=255, verbose_name="Ссылка на GitHub"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="image",
            field=models.ImageField(
                null=True, upload_to="personal", verbose_name="Картинка баннера"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="image_mobile",
            field=models.ImageField(
                null=True,
                upload_to="personal",
                verbose_name="Картинка баннера для мобилки",
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="linked_in",
            field=models.CharField(
                default="", max_length=255, verbose_name="Ссылка на LinkedIn"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="phone_number",
            field=models.CharField(
                default="", max_length=255, verbose_name="Номер телефона"
            ),
        ),
    ]
