# Generated by Django 4.2.7 on 2024-10-15 07:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0002_personalinfo_email_personalinfo_github_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(upload_to="additional", verbose_name="Иконка"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Дополнительная информация",
                "verbose_name_plural": "Дополнительная информация",
            },
        ),
    ]
