# Generated by Django 5.1.2 on 2024-10-15 07:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0003_additionalinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                ("text", ckeditor.fields.RichTextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Опыт",
                "verbose_name_plural": "Опыт",
            },
        ),
    ]
