# Generated by Django 5.1.2 on 2024-10-15 07:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0004_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="work_experience", verbose_name="Иконка компании"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="Название компании"),
                ),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Позиция на работе"),
                ),
                (
                    "responsibility",
                    ckeditor.fields.RichTextField(verbose_name="Обязанности на работе"),
                ),
            ],
            options={
                "verbose_name": "Опыт работы",
                "verbose_name_plural": "Опыт работы",
            },
        ),
    ]
