# Generated by Django 5.1.2 on 2024-10-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0007_additionalinfo_personal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalinfo",
            name="personal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_info",
                to="mainpage.personalinfo",
            ),
        ),
    ]
