# Generated by Django 4.2.7 on 2024-10-18 08:02

from django.db import migrations, models
import mainpage.utils


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0008_alter_additionalinfo_personal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalinfo",
            name="personal",
        ),
        migrations.AddField(
            model_name="workexperience",
            name="leadership",
            field=models.BooleanField(default=False, verbose_name="Лидерство"),
        ),
        migrations.AlterField(
            model_name="additionalinfo",
            name="icon",
            field=models.ImageField(
                upload_to=mainpage.utils.directory_path, verbose_name="Иконка"
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=mainpage.utils.directory_path,
                verbose_name="Картинка баннера",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="image_mobile",
            field=models.ImageField(
                null=True,
                upload_to=mainpage.utils.directory_path,
                verbose_name="Картинка баннера для мобилки",
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="resume_file",
            field=models.FileField(
                upload_to=mainpage.utils.directory_path, verbose_name="Файл резюме"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                upload_to=mainpage.utils.directory_path, verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image_mobile",
            field=models.ImageField(
                upload_to=mainpage.utils.directory_path,
                verbose_name="Картинка для мобилки",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="icon",
            field=models.ImageField(
                upload_to=mainpage.utils.directory_path, verbose_name="Иконка компании"
            ),
        ),
    ]
